from node:17.8.0

LABEL version="1.1.0"
LABEL description="we are the world furniture in the technology power and development"

WORKDIR /app/socialapp

run npm install && npm clean cache --force

CMD [ "package.json*","package-lock.json*","./" ]

COPY . .

CMD ["npm","run","dev"]

