import type { NextPage } from "next";
import Head from "next/head";
//all these lines of codes are imports and exports
import Image from "next/image";
import styles from "../styles/Home.module.css";
import green from "@mui/material/colors";
import {
  Checkbox,
  Box,
  AppBar,
  Typography,
  Card,
  Container,
} from "@mui/material";
import React, { useRef, useMemo, useEffect } from "react";
import {
  atom,
  selector,
  useRecoilStateLoadable,
  useRecoilValueLoadable,
} from "recoil";

//here are only overriden methods
const username = atom({
  key: "username",
  default: " aristide anderson " as string,
});

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>www.Lcenter.com</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Box sx={{ color: `${green}` }}>just ready to start and go</Box>
    </div>
  );
};

export default Home;
